### ISSUE TITLE
What's up with the directory structure? And coop maybe? :)

### ISSUE THREAD

**Issue by plajjan** [mitchellh/zig-build-zlib#1]
Hi Mitchell!

I've run into and used a few of your repos where you've put together a build.zig for some other C lib, like here and for pcre2, so first of all - thanks! also libxev looks awesome :)

I wonder though, why is this repos directory structure organized like this? I mean, isn't it better to fork the upstream repo and just add a build.zig? I've done that for a bunch of projects and upgrading the base lib is usually just a git rebase away, potentially fixing some issues... and it sort of feels like it's closer to upstreaming that way, no?

I see you have multiple repos organized just like this, and this is at least the second where we have overlap (the other is utf8proc, which I have a build.zig for over at https://github.com/actonlang/utf8proc/tree/zig-build). I would very much like to cooperative on these things in the zig community so that perhaps some of these build.zig files might actually be accepted into the upstream repo (I did get zig v0.11 fixes into the pcre2 one, yay!). I'm curious, what's the appeal to this sort of organization?

This isn't meant as any critique, if this is what works best for you that's cool too.

**Comment by mitchellh** [comment]
Hey, yeah forking and just adding a build.zig is easier but I find it really simple to maintain my own commit history and as you can see in my repos the `update.sh` is not very complicated. There's obvious downsides, mainly around supply chain security (for others, I trust myself of course and I do add the `verify.sh` to checksum the directory tree). 

My goal generally has been to make these projects for my own use cases, if someone else makes a better one that works for me I may update to it but I want to be able to strictly control the upstream commits for my downstream projects.
